### ISSUE TITLE
Initail fork/set up

### ISSUE THREAD

**Issue by camrun91** [gitaaronc/autohubpp#1]
I am going to try and get this set up and operational on my setup at home. I am running freenas with homeassistant and several other things in jails. I will place this in one and see if I can get it working. Do you have instructions on how you integrated the two?

**Comment by camrun91** [comment]
Ok I have my fork cloned to my server but can not get it to compile. I have installed all requirements but they are on the server level and not in the autohubpp directory.

**Comment by gitaaronc** [comment]
Create issue on my github so we don't pollute this one.

**Comment by gitaaronc** [comment]
Sorry didn't see that you did already.

**Comment by camrun91** [comment]
Haha I was thinking this is on yours... lol no problem

**Comment by gitaaronc** [comment]
Not sure what errors you receive. That said, you need to have websocketpp and restbed visible in your path. On linux I put websocketpp in /usr/include/websocketpp and restbed in /usr/include/restbed
You will also need to follow the instructions for compiling and installing restbed. https://github.com/Corvusoft/restbed.git

**Comment by gitaaronc** [comment]
I've added some basic instructions to the README.md file. Please take a look at it. Hopefully it helps.
You also want to update your copy of the repo. git pull origin dev
